### ISSUE TITLE
After reload and closing the issue shown the empty screen

### ISSUE THREAD

**Issue by nestoragent** [hcengineering/platform#4086]
**Summary**

If reload the page with an open issue and close it will show an empty screen

**Steps to reproduce:**

1. Login to platform
2. Go to the Tracker
3. Open any issue
4. Reload the page (F5)
5. Close the issue

**Actual Result**

Shown an empty screen

**Expected Result**

Should be shown the list of issues

**Comment by anotherpit** [comment]
Possible solutions:

1. Don’t show close icon at all when we know we won’t be able to handle close action properly.
2. Remember where we came from in a way that will survive page refresh
   2.1. URL - e.g. `workbench/PROJECT/tracker/ISSUE?from=PREV_URL`
   2.2. SessionStorage - will survive refresh, but unlike 2.1. is not shareable
3. Hardcode the page to get back to when the issue is closed, e.g. to All Issues
4. Some smart combination of all previous solutions

**Comment by BykhovDenis** [comment]
[Vyazovetskiy Petr](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=656604373f596f99f4124601&label=Vyazovetskiy%20Petr) When we resolve issue short link and it open now we should resolve default location (look `tracker-resources/issues/resolveLocation` )
