### ISSUE TITLE
Docker build error while running fast start script

### ISSUE THREAD

**Issue by vivek9patel** [hcengineering/platform#5280]
### Description of the issue

I am trying to setup the repo for development using the fast start script. And getting this error for 7 modules on `docker:build` step:

```bash
==[ FAILURE: 7 operations ]====================================================

--[ FAILURE: @hcengineering/collaborator (docker-build) ]----[ 1.57 seconds ]--

Command "build" not available in current context (myacicontext), you can use the "default" context to run this command
Error: Failed calling ../../common/scripts/docker_build.sh hardcoreeng/collaborator.  Exit code: 1

--[ FAILURE: @hcengineering/pod-account (docker-build) ]-----[ 0.90 seconds ]--

Command "build" not available in current context (myacicontext), you can use the "default" context to run this command
Error: Failed calling ../../common/scripts/docker_build.sh hardcoreeng/account.  Exit code: 1

--[ FAILURE: @hcengineering/pod-backup (docker-build) ]------[ 1.15 seconds ]--

... and so on
```

### Your environment

* Version of huly: 0.6.111
* Your operating system (and version): Mac OSX, M1

### Steps to reproduce

```
- git clone the repo
- sh ./scripts/fast-start.sh
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjE2MjMxNzI0N2IzZDJhZDI5MjMyMGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.3uv36wV8jXart17eIo8GGiihWdVOtFDgsewBeKSw2ag">Huly&reg;: <b>UBERF-6463</b></a></sub>

**Comment by thomas-x-69** [comment]
the same error for me and I tried to run it with the terminal, WSL, Git Bash, and PowerShell and still the same problem

**Comment by thomas-x-69** [comment]
@haiodo I want to contribute to completing my Software Engineer role application process, is there any solution?

**Comment by Mansvini** [comment]
**Credential Helper Configuration Troubleshooting**

If you're already logged in (to Docker) but continue to face issues, it could be related to Docker's credential helper, which is utilized to securely store credentials.

**Checking Docker Configuration**:
- Inspect your Docker configuration file, typically found at `~/.docker/config.json`, for the presence of `credsStore` or `credHelpers` fields.
- If a credential helper is configured, verify it's operating correctly. As a diagnostic step, you might consider temporarily removing this configuration to see if it addresses the issue. It's prudent to backup any configurations before making modifications.

To access your Docker directory, execute:
```
cd ~/.docker
```

To view your `config.json`, any of the following commands can be used:
- `cat ~/.docker/config.json`
- `nano ~/.docker/config.json`
- `vim ~/.docker/config.json`

In this file, look for "credsStore" or "credHelpers" entries, which dictate how Docker credentials are managed and stored. If you're troubleshooting Docker login issues or problems pulling images, making adjustments here could be necessary. Exercise caution when altering configuration files, and always backup the config file prior to making changes.

In my `config.json`, I encountered the following line:
```
"credsStore": "desktop",
```

**Resolution Steps**:
1. **Backup Your Configuration**: Prioritize backing up your current Docker configuration by copying the `config.json` file:
```
cp ~/.docker/config.json ~/.docker/config_backup.json
```

2. **Modify or Remove `credsStore`**: For troubleshooting, you may opt to modify or temporarily eliminate the `"credsStore": "desktop"` entry from your `config.json`. This adjustment causes Docker to default back to storing credentials directly within the `config.json` file rather than leveraging the desktop credentials store. To remove or comment out this line, use a text editor like nano:
```
nano ~/.docker/config.json
```
Then, remove or comment out the `"credsStore": "desktop",` line, save your changes, and exit the editor.

3. **Retry Docker Operations**: With the modification in place, attempt the Docker operations that were previously unsuccessful. If the credential store was the culprit, these operations might now proceed without issue.

4. **Revert If Necessary**: Should the removal of the `credsStore` configuration fail to solve your problem or introduce new issues, you can revert to your original configuration by restoring the backup:
```
cp ~/.docker/config_backup.json ~/.docker/config.json
```

5. **Further Troubleshooting**: Persisting problems might necessitate additional steps, such as ensuring you're logged into Docker via `docker login`, checking for network or proxy settings that could affect Docker's external registry communications, and reviewing Docker and system logs for potentially insightful error messages.

Altering the `credsStore` configuration is a useful step in pinpointing the issue. However, it's crucial to weigh the security implications and workflow needs before settling on a permanent resolution.

**Comment by vivek9patel** [comment]
@Mansvini this worked, thank you 🚀
