### ISSUE TITLE
endless loading screen

### ISSUE THREAD

**Issue by kulik8v** [hcengineering/platform#6994]
### Description of the issue

When creating a new project, it gets stuck on an endless loading screen

### Your environment

* Version of Huly - no idea (using vendor web version)
* Browser (and version) - firefox 131.0.3
* Your operating system (and version) - win11

### Steps to reproduce

Log into the account
Click 'Create Project'

![изображение](https://github.com/user-attachments/assets/2169b1cc-4552-4207-a1a5-b7c1318829c6)

**Comment by lexiv0re** [comment]
Hi @kulik8v, thanks for your interest in using Huly. I see that you are connecting to `front.hc.engineering` which is a staging server not suitable for production use. Where did you find this link? I'm curious because if any existing resources point to this url we should update them to use the correct one.
Please use this one instead to start working on the production server https://huly.io/signup.

**Comment by kulik8v** [comment]
Hi @lexiv0re, I received this link from @aplatoff  on January 26 when I asked him for access to the platform. Here is the screenshot)

![изображение](https://github.com/user-attachments/assets/9e554c4b-dc3d-48a0-ada8-72a509ac9c15)


And now I see that the project I asked about regarding the endless loading has been created. So, which link should I use to access and continue using the platform?

**Comment by lexiv0re** [comment]
@kulik8v thanks. For production use I'd recommend switching to `huly.io` as the pre-production server you had early access to might have unstable versions from time to time and more frequent upgrades causing work interruptions. If you want to move your old workspace data to `huly.io` we can help with that. If you are fine starting from scratch just create a new workspace on `huly.io`.
